package com.minecraftmc22.expenses.authentication

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.util.Log
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.firebase.auth.AuthCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.minecraftmc22.expenses.Application
import com.minecraftmc22.expenses.util.reactive.ReactiveTaskListener
import io.reactivex.Completable
import io.reactivex.Single

class AuthenticationManager(
    private val context: Context,
    private val firebaseAuth: FirebaseAuth
) {

    /**
     * Null while the bundled google-services.json carries no web OAuth client, which is
     * the case until the Google sign-in provider is enabled in the Firebase project.
     */
    private val googleSignInClient: GoogleSignInClient? = createGoogleSignInClient(context)

    // Current user

    fun isUserSignedIn(): Boolean {
        return firebaseAuth.currentUser != null
    }

    fun getCurrentUserId(): String? {
        return firebaseAuth.currentUser?.uid
    }

    fun getCurrentUserEmail(): String? {
        return firebaseAuth.currentUser?.email
    }

    fun getCurrentUserName(): String? {
        return firebaseAuth.currentUser?.displayName
    }

    // Sign in

    /**
     * Null when Google sign-in is not configured, see [googleSignInClient].
     */
    fun getGoogleSignInRequest(): Intent? {
        return googleSignInClient?.signInIntent
    }

    fun handleGoogleSignInResult(googleSignInResult: Intent): Completable {
        return getCredential(googleSignInResult).flatMapCompletable { signIn(it) }
    }

    private fun getCredential(googleSignInResult: Intent): Single<AuthCredential> {
        val getAccountTask = GoogleSignIn.getSignedInAccountFromIntent(googleSignInResult)
        return Single.create(ReactiveTaskListener(getAccountTask))
            .flatMap { account ->
                val idToken = account.idToken

                if (idToken.isNullOrEmpty()) {
                    // Google hands back an account without an ID token when
                    // requestIdToken() was given a client ID that does not belong to
                    // this app's Firebase project, which also happens when the signing
                    // certificate is not registered there. Without this check the null
                    // token becomes a credential that Firebase rejects without an
                    // explanation.
                    Single.error<AuthCredential>(
                        IllegalStateException(
                            "Google account has no ID token. The web client ID passed to " +
                                "requestIdToken() has to belong to the Firebase project of " +
                                "this app, and the signing certificate has to be registered there."
                        )
                    )
                } else {
                    Single.just(GoogleAuthProvider.getCredential(idToken, null))
                }
            }
    }

    private fun signIn(credential: AuthCredential): Completable {
        val signInTask = firebaseAuth.signInWithCredential(credential)
        return Completable.create(ReactiveTaskListener(signInTask))
    }

    // Sign out

    fun signOut(): Completable {
        val currentUser = firebaseAuth.currentUser

        if (currentUser == null) {
            Log.w(TAG, "Current user is null. No need to sign out.")
            return Completable.complete()
        }

        firebaseAuth.signOut()

        val account = GoogleSignIn.getLastSignedInAccount(context)
        val client = googleSignInClient

        return if (account == null || client == null) {
            // User signed in anonymously, or Google sign-in is not configured at all.
            // No need to sign out from Google.
            Completable.complete()
        } else {
            val signOutFromGoogle = client.signOut()
            Completable.create(ReactiveTaskListener(signOutFromGoogle))
        }
    }

    companion object {
        private const val TAG = "AuthenticationManager"

        private const val DEFAULT_WEB_CLIENT_ID_RESOURCE = "default_web_client_id"

        /**
         * Builds the Google sign-in client, or returns null when the project has no web
         * OAuth client. That id is generated by the google-services plugin out of the
         * `oauth_client` entries, so an empty `oauth_client` in google-services.json means
         * the Google sign-in provider has not been enabled in Firebase yet. The resource is
         * looked up by name so that such a configuration still compiles instead of failing
         * on an unresolved `R.string` reference.
         */
        private fun createGoogleSignInClient(context: Context): GoogleSignInClient? {
            val webClientId = getWebClientId(context) ?: return null

            val options = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(webClientId)
                .requestEmail()
                .build()

            return GoogleSignIn.getClient(context, options)
        }

        private fun getWebClientId(context: Context): String? {
            val id = context.resources.getIdentifier(
                DEFAULT_WEB_CLIENT_ID_RESOURCE,
                "string",
                context.packageName
            )

            return if (id == 0) null else context.getString(id)
        }
    }
}